ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    publish_tf: true
    print_diagnostics: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom

    # # Wheel odometry
    # odom0: /wheel/odom

    # # Fuse X position + X velocity from wheel odom
    # # [x, y, z, roll, pitch, yaw, vx, vy, vz, vroll, vpitch, vyaw, ax, ay, az]
    # odom0_config: [
    #   true,  false, false,
    #   false, false, false,
    #   true,  false, false,
    #   false, false, false,
    #   false, false, false
    # ]
    # odom0_differential: false
    # odom0_relative: false

    # ZED odometry
    odom0: /zed_front/zed_node/odom 

    # Fuse X, Y, and Yaw from ZED (2D pose)
    # (Leave velocities false to avoid double-fusing if wheel odom is your velocity source)
    odom0_config: [
      true,  true,  false,
      false, false, true,
      false, true, false,
      false, false, true,
      false, false, false
    ]
    odom0_differential: false
    odom0_relative: false
